/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                    "#004ac6",
        "on-primary":                 "#ffffff",
        "primary-container":          "#2563eb",
        "on-primary-container":       "#eeefff",
        "primary-fixed":              "#dbe1ff",
        "primary-fixed-dim":          "#b4c5ff",
        "on-primary-fixed":           "#00174b",
        "on-primary-fixed-variant":   "#003ea8",
        "inverse-primary":            "#b4c5ff",
        "surface-tint":               "#0053db",

        "secondary":                  "#565e74",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#dae2fd",
        "on-secondary-container":     "#5c647a",
        "secondary-fixed":            "#dae2fd",
        "secondary-fixed-dim":        "#bec6e0",
        "on-secondary-fixed":         "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",

        "tertiary":                   "#943700",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#bc4800",
        "on-tertiary-container":      "#ffede6",
        "tertiary-fixed":             "#ffdbcd",
        "tertiary-fixed-dim":         "#ffb596",
        "on-tertiary-fixed":          "#360f00",
        "on-tertiary-fixed-variant":  "#7d2d00",

        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",

        "background":                 "#f7f9fb",
        "on-background":              "#191c1e",
        "surface":                    "#f7f9fb",
        "surface-dim":                "#d8dadc",
        "surface-bright":             "#f7f9fb",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f4f6",
        "surface-container":          "#eceef0",
        "surface-container-high":     "#e6e8ea",
        "surface-container-highest":  "#e0e3e5",
        "on-surface":                 "#191c1e",
        "on-surface-variant":         "#434655",
        "surface-variant":            "#e0e3e5",
        "inverse-surface":            "#2d3133",
        "inverse-on-surface":         "#eff1f3",

        "outline":                    "#737686",
        "outline-variant":            "#c3c6d7",
      },
      spacing: {
        "sidebar-width": "260px",
        "gutter":        "24px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg":        ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-md":        ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm":       ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg":           ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md":           ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm":          ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
